### ISSUE TITLE
Project's wiki is empty

### ISSUE THREAD

**Issue by sambragg** [danthareja/contribute-to-open-source-server#1]
The wiki is currently empty but CONTRIBUTING.md contains links to an article in it (Setting up Git -
 line 43).

**Comment by danthareja** [comment]
Thanks for the issue @sambragg, I'll fix it shortly.

**Comment by danthareja** [comment]
The page has been added:

https://github.com/danthareja/contribute-to-open-source/wiki/Setting-up-Git
